apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: wisniewskikr/chrisblog-microservices_gateway:0.0.1
        ports:
        - containerPort: 8762
        env:
        - name: spring.application.name
          value: gateway
        - name: spring.config.import
          value: configserver:http://config:8888
        - name: LOKI_URL
          value: http://loki:3100
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8762
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8762
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 8762
      targetPort: 8762