version: "4"
services:

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
#    volumes:
#      - dbdata:/var/lib/mysq

  be:
    image: be:0.0.1
    container_name: be
    build:
      context: ./../chrisblog-microservices_be
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/database
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  fe:
    image: fe:0.0.1
    container_name: fe
    build:
      context: ./../chrisblog-microservices_fe
      dockerfile: Dockerfile
    environment:
      - api.url=http://be:8081
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s