global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'fe'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['fe:8080']
  - job_name: 'be'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['be:8081']
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8762']